version: "3"
services:
  celeste:
    build:
      context: ../
      dockerfile: ./containers/celeste/Dockerfile
    image: bbengfort/celeste
    init: true
    ports:
      - 10001:10001
    volumes:
      - ../fixtures:/data
    environment:
      - COSMOS_MAINTENACE=false
      - COSMOS_LOG_LEVEL=debug
      - COSMOS_CONSOLE_LOG=true
      - COSMOS_BIND_ADDR=:10001
      - COSMOS_AUTH_AUDIENCE=localhost:10001
      - COSMOS_AUTH_TOKEN_KEYS=26f1NOy89mwuIOCwlN66oC61WkF:/data/secrets/26f1NOy89mwuIOCwlN66oC61WkF.pem