name: CI
on:
  push:
    branches:
      - main
      - 'v*'
    tags:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: install
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: checkout
        uses: actions/checkout@v2

      - name: lint
        run: staticcheck ./...

  tests:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cosmos
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ./cosmos

      - name: install
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: dependencies
        run: |
          go version
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0

      - name: generate
        run: go generate ./...

      - name: unittest
        run: go test -v -coverprofile=coverage.txt -covermode=atomic -race ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cosmos
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ./cosmos

      - name: install
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: dependencies
        run: |
          go version
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0

      - name: generate
        run: go generate ./...

      - name: cosmos
        run: go build -o cosmos ./cmd/cosmos

      - name: celeste
        run: go build -o celeste ./cmd/celeste
